language: go

go:
  - 1.3
  - 1.4

env:
  - GOTAGS=restapi

install:
  - go get -d -v -t -tags "$GOTAGS" ./...
  - go build -v -tags "$GOTAGS" ./...

script: go test -v -tags "$GOTAGS" ./...
